[package]
name = "baml_elixir"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "baml_elixir"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.36.1", default-features = false, features = ["derive"] }
baml-runtime = { path = "baml/engine/baml-runtime", features = ["internal"] }
baml-types = { path = "baml/engine/baml-lib/baml-types" }
internal-baml-core = { path = "baml/engine/baml-lib/baml-core" }

[features]
default = ["nif_version_2_15"]
nif_version_2_15 = ["rustler/nif_version_2_15"]